title: Davenport Lab
description: Functional Genomics of Disease Response Heterogeneity
# baseurl: /
show_downloads: false
highlighter: rouge
google_analytics:
home: /
publications: /publications
people: /people
news: /news
contact: /contact
