title: Davenport Lab
description: Functional Genomics of Variation in Disease Response
# baseurl: /
show_downloads: false
highlighter: rouge
google_analytics:
home: /
research: /research
publications: /publications
people: /people
news: /news
contact: /contact
